In [ ]:


#1. Basic Array Creation
import numpy as np
#Create a 1D array
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)
#Create a 2D array
array_2d =np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2d)
#Create an array with zeros
zeros_array = np.zeros((3,3))
print("Zeros Array:\n",zeros_array)
#Create an array with ones
ones_array = np.ones((2,2))
print("Ones Array:\n",ones_array)
     
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]

#2.Array Operation
import numpy as np
#Create two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
#Addition
sum_array=np.add(a,b)
print("Sum:",sum_array)
#Subtraction
diff_array=np.subtract(a,b)
print("Difference:",diff_array)
#Multiplication
Product_array=np.multiply(a,b)
print("Product:",Product_array)
#Division
quotient_array=np.divide(a,b)
print("Quotient:",quotient_array)
     
Sum: [5 7 9]
Difference: [-3 -3 -3]
Product: [ 4 10 18]
Quotient: [0.25 0.4  0.5 ]

#3.Matrix Multiplication
import numpy as np
#Create two matrices
matrix_a=np.array([[1,2],[3,4]])
matrix_b=np.array([[5,6],[7,8]])
#Matrix multiplication
matrix_product=np.dot(matrix_a,matrix_b)
print("Matrix Product:\n",matrix_product)

     
Matrix Product:
 [[19 22]
 [43 50]]

#4.Broadcasting
import numpy as np
#Create an array and a scalar
array=np.array([1,2,3])
scalar=2
#Broadcasting
broadcasted_array=array*scalar
print("Broadcasted Array:",broadcasted_array)

     
Broadcasted Array: [2 4 6]

#5.Statistical Operations
import numpy as np
#Create an array
data=np.array([1,2,3,4,5])
#Mean
mean_value=np.mean(data)
print("Mean:",mean_value)
#Standard deviation
std_value=np.std(data)
print("Standard Deviation:",std_value)
#Sum
sum_value=np.sum(data)
print("Sum:",sum_value)
     
Mean: 3.0
Standard Deviation: 1.4142135623730951
Sum: 15

#6.Reshaping Arrays
import numpy as np
#Create a 1D array
array=np.array([1,2,3,4,5,6])
#Reshape to 2*3
reshaped_array=array.reshape((2,3))
print("Reshaped Array:\n", reshaped_array)
#Reshape to 3*2
reshaped_array=array.reshape((3,2))
print("Reshaped Array:\n",reshaped_array)
     
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]

#7.Element-wise Operation
import numpy as np
#create two arays
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
#Element-wise addition
add_result=array_a+array_b
print("Element-wise Addition:",add_result)
#Element-wise multiplication
multiply_result=array_a*array_b
print("Element-wise Multiplication:",multiply_result)
     
Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]

#8.Slicing and Indexing
import numpy as np
#Create a 2D array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
#Accessing a element
element=array_2d[1,1]
print("Element at[1,1]:",element)
#Accessing a column
column=array_2d[:,1]
print("Column 1:",column)

     
Element at[1,1]: 5
Column 1: [2 5 8]

#9.Creating Random Arrays
import numpy as np
#Create a random array
random_array=np.random.rand(3,3)
print("Random Array:\n",random_array)
#Create a random integer array
random_int_array=np.random.randint(0,10,(3,3))
print("Random Integer Array:\n",random_int_array)
     
Random Array:
 [[0.78606338 0.37376052 0.78489456]
 [0.22236633 0.09950456 0.18654124]
 [0.54300085 0.18708629 0.5959886 ]]
Random Integer Array:
 [[8 5 4]
 [4 1 6]
 [2 1 0]]

#10.Stacking and Concatenating Arrays
import numpy as np
#Create two arrays
array
     
array([1, 2, 3, 4, 5, 6])